spring:

  datasource:
    url: "jdbc:postgresql://localhost:5432/spring-hell"
    username: daniil
    password: daniil
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
