spring:

  datasource:
    url: "jdbc:postgresql://localhost:5432/spring-hell"
    username: daniil
    password: daniil
    driver-class-name: org.postgresql.Driver

  h2:
    hibernate:
      dialect: "org.hibernate.dialect.H2Dialect"
      hbm2ddl.auto: create-drop
      show_sql: true
      batch.size: 20
      current.session.context.class: org.springframework.orm.hibernate5.SpringSessionContext

  jpa:
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"